196 backward euler fortran
NCAR/musica pull request #210
Opened 2024-08-27 14:04 UTC by dwfncar

Added fortran API for Backward Euler solvers.
Made time_step and test_accuracy as inputs to test_multiple_grid_cells in test_micm_api.F90.

2024-08-27 15:11 UTC, boulderdaze approved these changes
Looks good!

2024-08-29 17:48 UTC, mattldawson requested changes
looks great! just a couple minor suggestions

2024-08-29 17:48 UTC, mattldawson commented on fortran/test/fetch_content_integration/test_micm_api.F90
> +      print *
please remove diagnostic output

2024-08-29 17:48 UTC, mattldawson commented on fortran/test/fetch_content_integration/test_micm_api.F90
> +    print *, 'test_multiple_grid_cells standard Rosenbrock'
please remove diagnostic output

2024-09-03 16:35 UTC, K20shores approved these changes

2024-09-09 20:50 UTC, mattldawson approved these changes
looks great!

2024-09-12 14:07 UTC, merged