Draft:Update MICM wrapper in Atmospheric Physics
NCAR/musica pull request #50
Opened 2023-11-03 23:50 UTC by boulderdaze

[Issue #48](https://github.com/NCAR/musica/issues/48l)

2023-11-20 23:58 UTC, mattldawson requested changes
Looks good! Just a couple comments/questions on where the creation/destruction of the solver should be

2023-11-20 23:58 UTC, mattldawson commented on Dockerfile.fortran-ubuntu
> +    && make install
```suggestion
# Install json-fortran
RUN cd json-fortran-8.2.0 \
    && mkdir build \
    && cd build \
    && cmake -D SKIP_DOC_GEN:BOOL=TRUE .. \
    && make install
```

2023-11-20 23:58 UTC, mattldawson commented on musica-fortran/src/micm/micm_core.F90
>          procedure :: create_solver => micm_create_solver
is this function needed? or can this all be handled in the constructor (`create_micm`)?

2023-11-20 23:58 UTC, mattldawson commented on .github/workflows/test.yml
> +  #     run: docker run --name test-container -t musica-fortran bash -c 'make test'
is this commented out because the intel image is still too large to run in GH actions?

2023-11-20 23:58 UTC, mattldawson commented on musica-fortran/src/micm/micm_core.F90
> +    end subroutine finalize
should this also free the solver?

2024-01-03 19:52 UTC, mattldawson requested changes
looks great! just a couple minor things

2024-01-03 19:52 UTC, mattldawson commented on CMakeLists.txt
> +message(STATUS "Making MUSICA-Fortran sources installable by the CAM-SIMA framework : ${MAKE_MUSICA_FORTRAN_INSTALLABLE}")
```suggestion
message(STATUS "Making MUSICA-Fortran sources installable : ${MAKE_MUSICA_FORTRAN_INSTALLABLE}")
```
We'll want to make sure the MUSICA library and interfaces are usable in any host application

2024-01-03 19:52 UTC, mattldawson commented on musica-fortran/src/micm/micm_core.F90
> +    end function micm_create_solver
Could this just be done in the constructor?

2024-01-04 19:23 UTC, mattldawson requested changes

2024-01-04 19:23 UTC, mattldawson commented on musica-fortran/test/test_musica_api.F90
> +        write(*,*) "  * [Fortran] Failed in creating solver"
Sorry, I missed this earlier - if this test is expected to successfully create a solver, I would add:
```
stop 3
```
to the block that catches failures creating the solver. This way the test will fail if there is a problem creating the solver.

2024-01-04 19:23 UTC, mattldawson commented on musica-fortran/test/test_musica_api_invalid_config.F90
> +        write(*,*) "  * [Fortran] Failed in creating solver"
similar to above, I would add:
```
stop 3
```
to blocks that should not be reached in the test

2024-01-05 21:43 UTC, K20shores approved these changes

2024-01-17 20:01 UTC, mattldawson approved these changes
looks great!

2024-01-17 20:11 UTC, merged